services:
  backend:
    image: node:20
    container_name: backend-container
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroes
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    image: node:20
    container_name: frontend-container
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  db_data:
